In [8]:
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
dadosfin = pd.read_csv("dados_financeiros_condominios.csv")

dadosopr = pd.read_csv("dados_operacionais_condominios.csv")

In [12]:

dadosfin.head()

,ID_Registro,ID_Condominio,Nome_Condominio,Data_Mes_Referencia,Receita_Bruta_Mensal,Receita_Liquida_Mensal,Total_Unidades,Unidades_Inadimplentes,Percentual_Inadimplencia,Total_Despesas_Mensal,Fluxo_de_Caixa_Mensal
0,1,c5d34d83-4e0c-42c5-8d57-64bbd55d069f,Condomínio Montenegro Residence,2020-01,67018.16,59402.46,88,10,11.36,8102.43,51300.03
1,2,d07bdd14-979b-41f2-b2b7-9b1af6f1f21e,Condomínio Ferreira Residence,2020-01,57765.09,47438.37,179,32,17.88,9441.55,37996.82
2,3,18b4ee3b-1516-4896-bf2f-c7eac1dd2d54,Condomínio Guerra Residence,2020-01,19432.14,17937.36,39,3,7.69,2075.79,15861.57
3,4,5abfa6ac-7a97-40b0-915f-0b8142987d34,Condomínio Ribeiro Residence,2020-01,52979.58,45301.38,69,10,14.49,5919.05,39382.33
4,5,91c5fba8-6d11-4437-adc7-f891bee1a2ad,Condomínio Siqueira Residence,2020-01,56193.78,51952.74,106,8,7.55,6031.92,45920.82

In [13]:
dadosopr.head()

,ID_Registro,ID_Condominio,Tipo_Registro,ID_Morador,Nome_Morador,Unidade,Descricao,Data_Criacao,Data_Resolucao,Tempo_Resolucao_Horas,Custo_Estimado,Tipo_Manutencao
0,1,5abfa6ac-7a97-40b0-915f-0b8142987d34,Ocorrencia,2253bd96-c1e9-44b3-a3d8-8c3825d75192,Luiz Henrique Melo,26.0,Reclamação Segurança,2024-05-15 19:28:31,2024-05-16 15:32:27.874681,20.07,NaN,NaN
1,2,4904f0c2-bf99-4483-bc47-e05dc99f4956,Ocorrencia,b3f6b63a-3028-47c2-b25a-0b23d818f628,Larissa Moreira,105.0,Reclamacao Barulho,2023-05-09 03:49:09,2023-05-10 09:27:15.792073,29.64,NaN,NaN
2,3,c5d34d83-4e0c-42c5-8d57-64bbd55d069f,Manutencao,NaN,NaN,NaN,Manutencao preventiva em área comum,NaN,NaN,NaN,8444.18,Preventiva
3,4,bd9794c1-886b-437e-9481-55285e96e64d,Ocorrencia,447a469a-a09c-46ba-ac1c-c39ccde14e97,Bianca Cardoso,10.0,Aluguel De Churrasqueira,2024-06-13 05:21:20,2024-06-13 15:08:12.711055,9.78,NaN,NaN
4,5,18b4ee3b-1516-4896-bf2f-c7eac1dd2d54,Ocorrencia,e802f244-4216-492f-ab77-8370d77f4dd2,Olívia Lima,33.0,Problema Vazamento,2023-04-19 19:10:13,2023-04-24 09:24:33.390701,110.24,NaN,NaN

In [14]:
dadosfin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 576 entries, 0 to 575
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID_Registro               576 non-null    int64
 1   ID_Condominio             576 non-null    object
 2   Nome_Condominio           576 non-null    object
 3   Data_Mes_Referencia       576 non-null    object
 4   Receita_Bruta_Mensal      576 non-null    float64
 5   Receita_Liquida_Mensal    576 non-null    float64
 6   Total_Unidades            576 non-null    int64
 7   Unidades_Inadimplentes    576 non-null    int64
 8   Percentual_Inadimplencia  576 non-null    float64
 9   Total_Despesas_Mensal     576 non-null    float64
 10  Fluxo_de_Caixa_Mensal     576 non-null    float64
dtypes: float64(5), int64(3), object(3)
memory usage: 49.6+ KB

In [15]:
dadosopr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1735 entries, 0 to 1734
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID_Registro            1735 non-null   int64
 1   ID_Condominio          1735 non-null   object
 2   Tipo_Registro          1735 non-null   object
 3   ID_Morador             845 non-null    object
 4   Nome_Morador           845 non-null    object
 5   Unidade                845 non-null    float64
 6   Descricao              1735 non-null   object
 7   Data_Criacao           845 non-null    object
 8   Data_Resolucao         845 non-null    object
 9   Tempo_Resolucao_Horas  845 non-null    float64
 10  Custo_Estimado         890 non-null    float64
 11  Tipo_Manutencao        890 non-null    object
dtypes: float64(3), int64(1), object(8)
memory usage: 162.8+ KB

In [16]:
# Obter os IDs de condomínio únicos de cada DataFrame
ids_financeiros = set(dadosfin['ID_Condominio'].unique())
ids_operacionais = set(dadosopr['ID_Condominio'].unique())

In [17]:
# Comparar os dois conjuntos de IDs
sao_iguais = ids_financeiros == ids_operacionais

# Exibir os resultados
print(f"Número de IDs únicos no dataset financeiro: {len(ids_financeiros)}")
print(f"Número de IDs únicos no dataset operacional: {len(ids_operacionais)}")
print(f"\nOs IDs de condomínio são os mesmos nos dois datasets? {sao_iguais}")

if not sao_iguais:
    print("\nOs seguintes IDs estão no dataset financeiro, mas não no operacional:")
    print(ids_financeiros - ids_operacionais)
    
    print("\nOs seguintes IDs estão no dataset operacional, mas não no financeiro:")
    print(ids_operacionais - ids_financeiros)

Número de IDs únicos no dataset financeiro: 12
Número de IDs únicos no dataset operacional: 12

Os IDs de condomínio são os mesmos nos dois datasets? True